### ISSUE TITLE
Folder "0info"

### ISSUE THREAD

**Issue by Sondr11** [gaosjlucky/PTAS#3]

**Comment by gaosjlucky** [comment]
For the frequency file, please refer to PTAS/db/nipptRESHAPE.tsv which should be generated first step.
And then please refer to the example.sh file.
The DBsnp and REFsnp files are directly generated by nipptRESHAPE.tsv.




















At 2023-12-18 23:27:38, "Sondr11" ***@***.***> wrote:

Hì.
Please help me!!!!

**Comment by Sondr11** [comment]
Thank you for your response.  I have another question: how is the snp list file formatted?  Before starting to use PTAS, I understand that I must custumine 3 files: snp list, frequency format file like nipptRESHAPE.tsv and referrence.fa file like nipptRESHAPE.hg19.fa.  Am I understanding this correctly?

**Comment by Sondr11** [comment]
in the file nipptRESHAPE.hg19.fa.  I understand that I have to custumine it according to my snp and the snp position is at 501 in the sequence like nipptRESHAPE.hg19.fa .  But how many nucleotides is the length of the sequence?

**Comment by Sondr11** [comment]
Please help me!

**Comment by gaosjlucky** [comment]
The length of the sequence is 1001 bp and the target site is at position 501.



At 2023-12-19 10:18:09, "Sondr11" ***@***.***> wrote:

in the file nipptRESHAPE.hg19.fa. I understand that I have to custumine it according to my snp and the snp position is at 501 in the sequence like nipptRESHAPE.hg19.fa . But how many nucleotides is the length of the sequence?

**Comment by Sondr11** [comment]
Hì.
I have custuminze the frequency file and hg19.fa file according to your instructions.  I tested it with 50 snp and used the sequencing data in the example folder and the command as per your instructions.  I see it has run to the call snp step but when it comes to the calculation step it has an error like this:
![IMG_20231225_084508_MP](https://github.com/gaosjlucky/PTAS/assets/113531212/de78b35e-4c6c-4335-afae-5d8649a67e61)

How do I fix that error?
If I use the gene sequencing data in the example folder.  What snp should I use to be able to run the above code without errors?
Thank you so much

**Comment by gaosjlucky** [comment]
cpan>

cpan>install Statistics::TTest

**Comment by Sondr11** [comment]
Hi.
Can you share with me some snp to run the appropriate code with 6 files in the example folder
Thank you

**Comment by gaosjlucky** [comment]
extract snp.lst as input file: sed -n '2,$p' nipptRESHAPE.tsv | awk '{print $1}'

**Comment by Sondr11** [comment]
Hi
I fixed the Statistics::TTest error by installing with --sudo. but I still get the error:
_use of uninitialized value $cnumraw in division (/) at -e line 453
use of uninitialized value $cratioraw in division (/) at -e line 453
Error in file (file, "rt"): cannot open the connection
Calls: read.table -> file
In addition:Warning message:
In file (file, "rt"): cannot open file '/home/son/NIPPT/PTAS/result/0info/cffDNA.txt: No such file or the directory:_

I ran the code according to the instructions using the gene sequencing file in the example folder and the list of SNPs in the attached file.
I understand that the above error occurs because my SNP list does not match the gene sequencing data file you provided, leading to the cffDNA file not being calculated. Do I understand that?
Can you share with me some snp to match the data file you provided in the example folder?
Thank you
[snp.txt](https://github.com/gaosjlucky/PTAS/files/13774953/snp.txt)

**Comment by gaosjlucky** [comment]
SNP0001
SNP0002
SNP0003
SNP0004
SNP0005
SNP0006
SNP0007
SNP0008
SNP0009
SNP0010
SNP0011
SNP0012
SNP0013
SNP0014
SNP0015
SNP0016
SNP0017
SNP0018
SNP0019
SNP0020
SNP0021
SNP0022
SNP0023
SNP0024
SNP0025
SNP0026
SNP0027
SNP0028
SNP0029
SNP0030
SNP0031

**Comment by gaosjlucky** [comment]
You can also use the following command line： "sed -n '2,$p' nipptRESHAPE.tsv | awk '{print $1}'"

**Comment by Sondr11** [comment]
Hi
I used the snp file according to your instructions
SNP0001
SNP0002
...
and run the following command:
_perl '/home/son/NIPPT/PTAS/ptas.pl' --snp '/home/son/NIPPT/PTAS/custom/ref_example/snp' --f1 '/home/son/NIPPT/PTAS/example/GF_1 .fq.gz' --f2 '/home/son/NIPPT/PTAS/example/GF_2.fq.gz' --m1 '/home/son/NIPPT/PTAS/example/GM_1.fq.gz' --m2 '/home/son/NIPPT/PTAS/example/GM_2.fq.gz' --c1 '/home/son/NIPPT/PTAS/example/GC_1.fq.gz' --c2 '/home/son/NIPPT/ PTAS/example/GC_2.fq.gz' --out '/home/son/NIPPT/PTAS/result'_
I get the error:Step0 failed!
I looked at the code in the ptas.pl file and saw that
_open SNP,"<$snp_list" or die($!);
while (<SNP>){
  chomp;
  if ($_ =~ /^rs\d+$/){
   $need_snp{$_}++;
   $snp_count++;
  }else{
   print ER "! Reference establishment failed, please check the format of your list.\n";
   die("Step0 failed!\n");
  }_
I understand that the names of SNPs must have the letter "rs"

**Comment by Sondr11** [comment]
Hi.
In the ptas.pl file I have used the code
_open SNP,"<$snp_list" or die($!);
while (<SNP>){
  chomp;
  if ($_ =~ /^rs\d+$/){
   $need_snp{$_}++;
   $snp_count++;
  }else{
   print ER "! Reference establishment failed, please check the format of your list.\n";
   die("Step0 failed!\n");
  }_
I changed 'rs'='snp' and used list SNPT as you instructed, it worked, but it still reported the error:
_Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:_
_Print file(file, "rt") :
   cannot open file '/home/son/NIPPT/PTAS/result/0info/cffDNA.txt': No such file or directory
Execution halted
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
Print file(file, "rt") :
   cannot open file '/home/son/NIPPT/PTAS/result/0info/depth.txt': No such file or directory_
How are the two files cffDNA.txt and depth.txt created?

**Comment by gaosjlucky** [comment]
In order to hide personal genetic information, we hide the rsID. The code has been modified, please test it.

**Comment by Sondr11** [comment]
> In order to hide personal genetic information, we hide the rsID. The code has been modified, please test it.

**Comment by Sondr11** [comment]
Hi
It ran successfully.
With the sample in the example. Is it related to blood and what are the CPE and CPI indexes?
Thank you
